build:
    environment:
        php: '7.4.0'
            
    project_setup:
        before:
            - mysql -e "CREATE DATABASE IF NOT EXISTS testimonials"
    
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=coverage.xml'
                coverage:
                    file: 'coverage.xml'
                    format: 'clover'

before_commands:
    - "composer install --prefer-source"

tools:
    php_code_coverage:
        test_command: vendor/bin/phpunit

checks:
    php:
        code_rating: true
        duplication: true
        
tools:
    external_code_coverage: true